version: '3.9'

services:
  telegram-bot:
    build: ./telegram-bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - api-wrapper
    restart: unless-stopped

  api-wrapper:
    build: ./42-api-wrapper
    container_name: api_wrapper
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TOK_URL=${TOK_URL}
      - API_URL=${API_URL}
      - SCOPES=${SCOPES}
    ports:
      - "5000:5000"
    restart: unless-stopped
